# Generated by Django 2.1.5 on 2020-03-25 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='Library', max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='abs@gmail.com', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(blank=True)),
                ('borrowed_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('return_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 4, 16, 10, 24, 737311))),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 25, 16, 10, 24, 736269))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.Author')),
            ],
        ),
    ]
